package mmc.warehousemanagementsystem.mapper;

import java.util.List;
import mmc.warehousemanagementsystem.entity.Admins;
import mmc.warehousemanagementsystem.entity.AdminsExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AdminsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    long countByExample(AdminsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    int deleteByExample(AdminsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    int insert(Admins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    int insertSelective(Admins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    List<Admins> selectByExampleWithRowbounds(AdminsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    List<Admins> selectByExample(AdminsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    Admins selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    int updateByExampleSelective(@Param("record") Admins record, @Param("example") AdminsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    int updateByExample(@Param("record") Admins record, @Param("example") AdminsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    int updateByPrimaryKeySelective(Admins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    int updateByPrimaryKey(Admins record);
}