package mmc.warehousemanagementsystem.entity;

public class Admins {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.id
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.name
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.password
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.phone
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.token
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.manage_warehouse
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    private Long manageWarehouse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.gmt_created
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    private Long gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.gmt_modified
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.id
     *
     * @return the value of admins.id
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.id
     *
     * @param id the value for admins.id
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.name
     *
     * @return the value of admins.name
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.name
     *
     * @param name the value for admins.name
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.password
     *
     * @return the value of admins.password
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.password
     *
     * @param password the value for admins.password
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.phone
     *
     * @return the value of admins.phone
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.phone
     *
     * @param phone the value for admins.phone
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.token
     *
     * @return the value of admins.token
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.token
     *
     * @param token the value for admins.token
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.manage_warehouse
     *
     * @return the value of admins.manage_warehouse
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public Long getManageWarehouse() {
        return manageWarehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.manage_warehouse
     *
     * @param manageWarehouse the value for admins.manage_warehouse
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public void setManageWarehouse(Long manageWarehouse) {
        this.manageWarehouse = manageWarehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.gmt_created
     *
     * @return the value of admins.gmt_created
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public Long getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.gmt_created
     *
     * @param gmtCreated the value for admins.gmt_created
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public void setGmtCreated(Long gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.gmt_modified
     *
     * @return the value of admins.gmt_modified
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.gmt_modified
     *
     * @param gmtModified the value for admins.gmt_modified
     *
     * @mbg.generated Fri Sep 09 11:54:38 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}